// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyFiles(arg1:Array<string>,arg2:string):Promise<void>;

export function GetHomeDir():Promise<string>;

export function ScanDirectory(arg1:string):Promise<main.FileNode>;

export function SearchFiles(arg1:string,arg2:string):Promise<Array<main.FileNode>>;
